// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Admin } from "./tables/Admin.sol";
import { SpawnCount } from "./tables/SpawnCount.sol";
import { ChestPurchases } from "./tables/ChestPurchases.sol";
import { ItemPrice } from "./tables/ItemPrice.sol";
