[profile.default]
solc = "0.8.30"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
verbosity = 2
src = "src"
test = "test"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]
remappings = [
  "forge-std/=node_modules/forge-std/src/",
  "@latticexyz/=node_modules/@latticexyz/",
  "@dust/=node_modules/@dust/",
  "solady/=node_modules/solady/src/",
  "@openzeppelin/=node_modules/@openzeppelin/",
]
script_execution_protection = false
dynamic_test_linking = true
always_use_create_2_factory = true

[fmt]
ignore = ['**/codegen/**/*.sol']
sort_imports = true
tab_width = 2
bracket_spacing = true

[profile.local]
eth_rpc_url = "http://127.0.0.1:8545"

[profile.garnet]
eth_rpc_url = "https://rpc.garnetchain.com"

[profile.pyrope]
eth_rpc_url = "https://rpc.pyropechain.com"

[profile.redstone]
eth_rpc_url = "https://rpc.redstonechain.com"
